### ISSUE TITLE
EZ Villagers + Carryon conflict

### ISSUE THREAD

**Issue by ShyNieke** [NFINIT-Labs/beyond-fantasy#10]
It seems like Carry on is preventing villagers from being picked up for EZ villagers most of the time, I was able to convert a villager to an EZ villager at random and this villager now seems to be infinite placable.

**Comment by ShyNieke** [comment]
It seems like jumping while holding sneak allows you to more consistently pick up villagers, there is still a chance this fails but this is how I got a few villagers

**Comment by knoxhack** [comment]
should be fixed
