### ISSUE TITLE
Carry on the companions

### ISSUE THREAD

**Issue by xaviernicolax** [NFINIT-Labs/beyond-fantasy#15]
I have a small problem,
I accidentally picked up a fairy as a companion that you get as a quest reward.
With what I assume is the Carry on mod as I shift clicked right while looking at her.
This now locks me out of all game interactions, and even when I disconnect from the server or /kill I always reappear with the fairy in my hands without being able to do anything else :/.

**Comment by knoxhack** [comment]
should be fixed
