### ISSUE TITLE
Crashes constantly

### ISSUE THREAD

**Issue by Zarvera** [NFINIT-Labs/beyond-fantasy#16]
Well, it was somewhat fun while it lasted, but the pack rather quickly turned into a total crashfest. I just had like 3 crashes for just shift-clicking stuff into my chest, after avoiding doing that i now had 3 crashes for just walking into my mines and gave up.
Worst of all, all the crashes since after removing the callable horses mod were log-less. They produce no reports. Just "woops sorry exit code 1 k bye" so i can't really add anything of substance to the report.

**Comment by knoxhack** [comment]
Sorry to hear that, most of those crashes are already known but some devs are taking longer on fixing them bugs, for now Im releasing version 1.1.0 with the removal of the mods causing major crashes until their dev fix the bugs.

**Comment by Zarvera** [comment]
Eh, i'm cooling off and trying to avoid things that crash systematically.
Good to hear that fixes are on the way, though i'm not entirely sure if it's even "those" crashes as mine leave 0 logs.
Still, the more stable the better

**Comment by Vercalos** [comment]
[hs_err_pid28344.log](https://github.com/NFINIT-Labs/beyond-fantasy/files/12920111/hs_err_pid28344.log)

**Comment by Zarvera** [comment]
> [hs_err_pid28344.log](https://github.com/NFINIT-Labs/beyond-fantasy/files/12920111/hs_err_pid28344.log)

Ayep. I've literally just figured it out (at least i hope i did) and was going here to report.
Turned out there was a way to turn application log output on CF app and yeah, the "crashes" i've been experiencing were actually not MC crashes but this - JVM shutting off due to access violation in jemalloc.dll
As far as i understood it's either a JRE or GPU drivers issue.
Cleaned up my drivers with DDU and reinstalled and also went on and forceinstalled\updated Java just in case.
So far i haven't been thrown out of the game once, though i still have to check out my mines
