### ISSUE TITLE
No nether access

### ISSUE THREAD

**Issue by Zarvera** [NFINIT-Labs/beyond-fantasy#18]
Uhh so i killed the Leviathan and the quest that is supposed to grant access to the Nether sent 2 invalid commands and now i have neither access to the Nether nor that quest to trigger it
>Incorrent argument for command: grant

Also the Tidla Claw from Leviathan is all buggy and janky, but i see no github for the mod even

**Comment by knoxhack** [comment]
should be fixed in 1.2.0
