### ISSUE TITLE
Crash after death

### ISSUE THREAD

**Issue by ShyNieke** [NFINIT-Labs/beyond-fantasy#3]
Hi. I just installed the pack, died, walked back to my grave and are now met with a permanent crash to launcher upon joining my world

Below is the crashlog I am getting
https://gist.github.com/ShyNieke/9309eb348e649186fea628c474f991ed

**Comment by knoxhack** [comment]
https://github.com/Asek3/Rubidium/issues/625

**Comment by Mrbysco** [comment]
> Hi. I just installed the pack, died, walked back to my grave and are now met with a permanent crash to launcher upon joining my world
> 
> Below is the crashlog I am getting https://gist.github.com/ShyNieke/9309eb348e649186fea628c474f991ed

Have you tried to see if [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) works as a replacement for Rubidium?

**Comment by ShyNieke** [comment]
I just tried this and am able to play the pack without any issue

**Comment by knoxhack** [comment]
Implemented in 1.0.3, let me know if the update fixes it

**Comment by ShyNieke** [comment]
This crash is fixed but now I am noticing a new crash when it's raining 
https://gist.github.com/ShyNieke/1afe10eaa48262e2d64b6febc96625c7

Asked Bysco and he pointed out that it's the physics mod, manually removing the mod fixes that crash

**Comment by Mrbysco** [comment]
I've reported the crash to the dev from Embeddium

**Comment by knoxhack** [comment]
Fixed
