### ISSUE TITLE
Farmland not hydrating and crops not growing

### ISSUE THREAD

**Issue by ShyNieke** [NFINIT-Labs/beyond-fantasy#6]
I am unsure if this is actually a bug but I am unable to find any info on this in the pack or on the official pack page.

When there is water near my farmland it doesn't get hydrated and crops seem to not grow or extremely slowly. I managed to capture a creature which is applying the bone meal effect to my crops which is the only source of food I have.

**Comment by knoxhack** [comment]
Fixed in 1.0.5
