### ISSUE TITLE
Minecolonies crash

### ISSUE THREAD

**Issue by ShyNieke** [NFINIT-Labs/beyond-fantasy#9]
In version 1.0.6 of the pack Minecolonies is crashing when trying to place down structures, Updating the mod fixes this crash :)

On a slight different note, I am loving the pack <3

**Comment by knoxhack** [comment]
Thanks, will update it on next update. 

Glad you like the pack, enjoy it 🙂

**Comment by ShyNieke** [comment]
Don't want to open a new issue just to ask this, do you accept mod suggestions?

**Comment by knoxhack** [comment]
Yes of course, as long a it doesn't break the modpack progression or theme I'm open to suggestions ^^

**Comment by ShyNieke** [comment]
I would suggest my own passion product Statues but unsure if the upgrades for it would conflict with the pack theme (Also planning on a big content update soon which adds a handful of missing mobs)

The other mod I would suggest is flower patch a mod by Bysco and I which just allows multiple of the same flower in one block space

**Comment by knoxhack** [comment]
should be fixed
